{% set name = "karchive" %}
{% set version = "5.74.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/karchive-{{ version }}.zip
  sha256: 9c2c5c35f816eaf8511c58459ccb9177c31b7ba1c640d5a8955d7c6aa276ed63

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('karchive', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
  host:
    - qt
    - xz
    - zlib
    - bzip2
  run:
    - xz
    - zlib
    - bzip2

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Archive.so

about:
  home: https://api.kde.org/frameworks/karchive/html/index.html
  license: BSD-2-Clause AND LGPL-2.0-only AND LGPL-2.0-or-later AND LGPL-3.0-only AND LicenseRef-KDE-Accepted-LGPL
  license_family: GPL
  license_file:
    - LICENSES/BSD-2-Clause.txt
    - LICENSES/LGPL-2.0-only.txt
    - LICENSES/LGPL-2.0-or-later.txt
    - LICENSES/LGPL-3.0-only.txt
    - LICENSES/LicenseRef-KDE-Accepted-LGPL.txt
  summary: Reading, creating, and manipulating file archives
  description: |
    KArchive provides classes for easy reading, creation and manipulation of "archive"
    formats like ZIP and TAR. It also provides transparent compression and decompression of data,
    like the GZip format, via a subclass of QIODevice.
  doc_url: https://api.kde.org/frameworks/karchive/html/index.html
  dev_url: https://cgit.kde.org/karchive.git/tree

extra:
  recipe-maintainers:
    - scopatz
