{% set name = "karchive" %}
{% set version = "5.71.0" %}
{% set major_minor = ".".join(version.split(".")[:2]) %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.kde.org/stable/frameworks/{{ major_minor }}/karchive-{{ version }}.tar.xz
  sha256: cc81e856365dec2bcf3ec78aa01d42347ca390a2311ea12050f309dfbdb09624

build:
  number: 0
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('karchive', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - extra-cmake-modules >={{ version }}
  host:
    - qt
    - xz
    - zlib
    - bzip2
  run:
    - xz
    - zlib
    - bzip2

test:
  commands:
    - test -f ${PREFIX}/lib/libKF5Archive.so

about:
  home: https://api.kde.org/frameworks/karchive/html/index.html
  license: GPL-v2
  license_family: GPL
  license_file: COPYING
  summary: Reading, creating, and manipulating file archives
  description: |
    KArchive provides classes for easy reading, creation and manipulation of "archive"
    formats like ZIP and TAR. It also provides transparent compression and decompression of data,
    like the GZip format, via a subclass of QIODevice.
  doc_url: https://api.kde.org/frameworks/karchive/html/index.html
  dev_url: https://cgit.kde.org/karchive.git/tree

extra:
  recipe-maintainers:
    - scopatz
