travis:
  secure:
    BINSTAR_TOKEN: EC3Z+nNQeSYZnFTZ59IG4jBl7QdtGbqRip0S3qLfmaCh6B2pOMyVZv4QU8VtbaIj3jJKSUvV+5J6wYZNbyPVBW7lNwBaFz3/GfpGL2Dxb1dALLN2bcmmG/kjlBb93pX7PlEhsqu9cQxuws8M1sY6TcJvtx+DMXR3NlkfC4HzBICK2K+kPspyu024QlFJ7jp2W8jl1RlXhf9fBZP3K9dwRgWpkHc2fCJat5q9mOrSMlyCuUgvuy8+BkGTr42g/KvP9Goaxsgg+BgKzvjt/hQgjj3rttchIXt7ux1oqvDFMJ63gsD8yjeE0O6NevuT7sNAYvEW1nkzxwUTXpLn2+ssSUxhcUG3743hrYSagQnz3EgPAYIMsff/2piupkKS/xaw6qeyxsc0MWVJ1vAyI4Pp+3eiwLeYpp3VGFwCLm3JvfocG2/P2ED/GRRP4pi+OYsI4LKtnuVKv30xr7S8ndnp0+ZMiibZ4N6RQ/s4RBPE/j5exaNvqWgi74nTPAKTD7HQKpZMNKucSVwCKm+gVl+18hTb8NWygV2lZ1QuINxrItVE+VEtfRg5eJEKqyAouZat1PjFC0xioVMaWsROIom/ZR4LvKwF1TB54/NSmNstb/sQbGArh4GUVqf5AMD0Gghu7nt5ogqhveAzPDsSWFbKLLI7dQiGNWxSpy6pF5GIlrI=
conda_forge_output_validation: true
bot:
  check_solvable: True
